# CMake generated Testfile for 
# Source directory: /home/xxx/Desktop/CON/con2526_g321/task-5/tests
# Build directory: /home/xxx/Desktop/CON/con2526_g321/task-5/_build/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(arp.req.reply "/usr/bin/cmake" "-D" "PROGRAM:STRING=/home/xxx/Desktop/CON/con2526_g321/task-5/_build/pinger" "-D" "ARGS:STRING=--respond;11:22:33:44:55:66;192.168.56.101" "-D" "INPUT_FILE:STRING=/home/xxx/Desktop/CON/con2526_g321/task-5/tests/arp.req.pcapng;--csv" "-D" "OUTPUT_FILE:STRING=arp.req.out.cap" "-D" "COMPARE_TOOL:STRING=diff;--strip-trailing-cr" "-D" "PRE_DELETE_COMPARE_FILES:BOOL=true" "-D" "COMPARE_FILES:STRING=arp.req.csv" "-D" "REFERENCE_FILES:STRING=/home/xxx/Desktop/CON/con2526_g321/task-5/tests/arp.req.reply.csv" "-D" "RETURN_VALUE:STRING=COMBINED" "-P" "/home/xxx/Desktop/CON/con2526_g321/task-5/cmake/scripts/run.cmake")
set_tests_properties(arp.req.reply PROPERTIES  WORKING_DIRECTORY "/home/xxx/Desktop/CON/con2526_g321/task-5/_build/tests" _BACKTRACE_TRIPLES "/home/xxx/Desktop/CON/con2526_g321/task-5/tests/CMakeLists.txt;1;add_test;/home/xxx/Desktop/CON/con2526_g321/task-5/tests/CMakeLists.txt;0;")
add_test(arp.req.noreply "/usr/bin/cmake" "-D" "PROGRAM:STRING=/home/xxx/Desktop/CON/con2526_g321/task-5/_build/pinger" "-D" "ARGS:STRING=--respond;11:22:33:44:55:66;192.168.56.102" "-D" "INPUT_FILE:STRING=/home/xxx/Desktop/CON/con2526_g321/task-5/tests/arp.req.pcapng;--csv" "-D" "OUTPUT_FILE:STRING=arp.req.noreply.out.cap" "-D" "COMPARE_TOOL:STRING=diff;--strip-trailing-cr" "-D" "PRE_DELETE_COMPARE_FILES:BOOL=true" "-D" "COMPARE_FILES:STRING=arp.req.noreply.csv" "-D" "REFERENCE_FILES:STRING=/home/xxx/Desktop/CON/con2526_g321/task-5/tests/arp.req.noreply.csv" "-D" "RETURN_VALUE:STRING=COMBINED" "-P" "/home/xxx/Desktop/CON/con2526_g321/task-5/cmake/scripts/run.cmake")
set_tests_properties(arp.req.noreply PROPERTIES  WORKING_DIRECTORY "/home/xxx/Desktop/CON/con2526_g321/task-5/_build/tests" _BACKTRACE_TRIPLES "/home/xxx/Desktop/CON/con2526_g321/task-5/tests/CMakeLists.txt;14;add_test;/home/xxx/Desktop/CON/con2526_g321/task-5/tests/CMakeLists.txt;0;")
add_test(arp.req+3xicmp_echo.reply "/usr/bin/cmake" "-D" "PROGRAM:STRING=/home/xxx/Desktop/CON/con2526_g321/task-5/_build/pinger" "-D" "ARGS:STRING=--respond;11:22:33:44:55:66;192.168.56.101" "-D" "INPUT_FILE:STRING=/home/xxx/Desktop/CON/con2526_g321/task-5/tests/arp.req+3xicmp_echo.pcapng;--csv" "-D" "OUTPUT_FILE:STRING=arp.req+3xicmp_echo.out.cap" "-D" "COMPARE_TOOL:STRING=diff;--strip-trailing-cr" "-D" "PRE_DELETE_COMPARE_FILES:BOOL=true" "-D" "COMPARE_FILES:STRING=arp.req+3xicmp_echo.csv" "-D" "REFERENCE_FILES:STRING=/home/xxx/Desktop/CON/con2526_g321/task-5/tests/arp.req+3xicmp_echo.reply.csv" "-D" "RETURN_VALUE:STRING=COMBINED" "-P" "/home/xxx/Desktop/CON/con2526_g321/task-5/cmake/scripts/run.cmake")
set_tests_properties(arp.req+3xicmp_echo.reply PROPERTIES  WORKING_DIRECTORY "/home/xxx/Desktop/CON/con2526_g321/task-5/_build/tests" _BACKTRACE_TRIPLES "/home/xxx/Desktop/CON/con2526_g321/task-5/tests/CMakeLists.txt;27;add_test;/home/xxx/Desktop/CON/con2526_g321/task-5/tests/CMakeLists.txt;0;")
